<a href="https://colab.research.google.com/github/JiUUoong/CODE/blob/main/RNN%EC%8B%A0%EA%B2%BD%EB%A7%9D%EB%AA%A8%EB%8D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 밑바닥부터 시작하는 딥러닝2(한빛미디어)에서 제공하는 깃헙 코드 클론하기
!git clone https://github.com/yonghyunk1m/deep-learning-from-scratch-2.git

In [ ]:
# Google Colab 한글 폰트 지원 (Matplotlib 등 한글 깨짐현상 방지)
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf
# 셀 실행 후 '런타임 - 런타임 다시 시작'

In [ ]:
# CH01 디렉토리로 이동하기
%cd "/content/deep-learning-from-scratch-2/ch01"
# colab - %는 파일 전체에서 적용, !는 cell 레벨에서 적용의 차이

In [ ]:
# 현재 디렉토리 확인하기
!pwd

# CH 01

넘파이의 ndarray

In [ ]:
import numpy as np
x = np.array([0,1,2])
x.__class__
# x=x.reshape(1,3)
print(x.shape)
x.ndim


(3,)


1

In [ ]:
W = np.array([ [0,1,2] , [3,4,5] ])
W.shape
W.ndim

2

In [ ]:
|print(type(x))

<class 'numpy.ndarray'>


In [ ]:
int("010", base=2)

2

In [ ]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if 

In [ ]:
W = np.array([[0,1,2], [3,4,5] ])
X = np.array([[1, 1, 1], [2, 2, 2]])
W*X

array([[ 0,  1,  2],
       [ 6,  8, 10]])

In [ ]:
arr1 = np.random.randn(15).reshape(5,3).T
arr2 = np.random.randn(15).reshape(3,5)
arr1+arr2

array([[-3.27144776,  0.72685623, -1.02589299, -3.80321154, -1.19715503],
       [ 0.20807825, -1.49439374,  0.1409938 ,  2.29671472, -0.71025195],
       [ 0.47115005, -0.70706145, -0.28676594,  2.0053052 , -0.16084327]])

In [ ]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.dot(a,b)
print(a@b)
print(a*b)

A = np.array([[1,2], [3,4]])
B = np.array([[1,1], [2,2]])
print(np.matmul(A, B))
print(A@B)

20
[ 2  6 12]
[[ 5  5]
 [11 11]]
[[ 5  5]
 [11 11]]


In [ ]:
x = np.random.randn(10, 2) # input layer
W = np.random.randn(2,4) # Weight
b = np.random.randn(4) # bias
h = np.matmul(x, W) + b #(10,4)
print(h.shape)

(10, 4)


In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [ ]:
sigmoid(-10000)

<ipython-input-28-ebbe1fbd659a>:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


0.0

시그모이드 구현

신경망 구현

In [ ]:
import numpy as np

def sigmoid(x):
  return 1 / (1+np.exp(-x))

N = 10
D = 2
H = 4
C = 3

x = np.random.randn(N, D)
W1 = np.random.randn(D, H)
b1 = np.random.randn(H)
W2 = np.random.randn(H, C)
b2 = np.random.randn(C)

h = x @ W1 + b1
a = sigmoid(h)
y = a @ W2 + b2

print(y)

[[2.17734091 1.51384635 1.35990231]
 [1.7973959  1.82629154 2.08966154]
 [1.72928426 1.93300492 2.29198676]
 [2.41510607 1.3614287  0.64141908]
 [1.98804396 1.65838634 1.75285245]
 [2.0878709  1.60063262 1.53352954]
 [1.94569169 1.71908126 1.78489098]
 [2.13782154 1.59502816 1.38624119]
 [1.89688907 1.72163471 1.92946591]
 [2.31446272 1.44875154 0.96558018]]


소프트맥스 구현

In [ ]:
import numpy as np

def softmax2D(x):
  y = np.zeros_like(x)
  for idx, sample in enumerate(x):
    y[idx] = softmax(sample)
  return y

In [ ]:
import numpy as np
class SampleNet :

   def __init__(self, I, H, O):
    I.H.O = I,H, O

    W1 = np.random.randn(I, H)
    b1 = np.random.randn(H)


In [ ]:
import numpy as np

def softmax(x): # (N,)
  tmp = np.exp(x)
  sum = np.sum(tmp)
  return tmp/sum # (N,)

x = np.array([[2.560, 0.817, -2.332]])
y = softmax(x)
print(y)
np.sum(y)

[[0.84566523 0.14798687 0.0063479 ]]


0.9999999999999999

In [ ]:
a = np.array([0,1,2])
print(np.exp(a))
np.exp(a)/2

[1.         2.71828183 7.3890561 ]


array([0.5       , 1.35914091, 3.69452805])

In [ ]:
np.sum(a)

3

Sigmoid와 Affine 계층(Layer) 구현

In [ ]:
import numpy as np

class Sigmoid:
  def __init__(self):
    self.params = []

  def forward(self, x):
    return 1/ (1+np.exp(-x))

class Affine:
  def __init__(self, W, b):
    self.params=[W,b]

  def forward(self, x):
    W, b = self.parms
    out = x@W + b
    return out

In [ ]:
a = Sigmoid()
b = Sigmoid()

Sigmoid
Sigmoid


In [ ]:
class Bread:
  def __init__(self):
    self.flavor = 'red_bean'
  def change_flavor(self, flavor):
    self.flavor = flavor
  def print_flavor(self):
    print(self.flavor)

In [ ]:
red_bean_bread = Bread()

In [ ]:
red_bean_bread.print_flavor()

red_bean


SampleNet 구현

In [ ]:
import numpy as np

def softmax2D(x):
  y

MatMul 노드 구현

In [ ]:
class MatMul:
  def __init__(self, W):
    self.params = [W]
    self.grads = [np.zeros_like(W)]
    self.x = None

  def forward(self, x):
    W, _ = self.forward
    out = np.matmul(x, W)
    self.x = x
    return out

  def backward(self, dout):
    W, _ = self.params
    dx = np.matmul(dout, W.T)
    dW = np.matmul(self.x.T, dout)
    self.grads[0][...] = dW

    return dx


분기노드의 순전파와 역전파 구현 예시

In [ ]:
import numpy as np

N, D = 10, 3

x= np.random.randn(1,D)
y = np.repeat(x, N, axis = 0)

dy = np.random.randn(N, D)
dx = np.random.randn(dy, axis=0, keepdims = True)

print(dx)

TypeError: ignored

In [ ]:
import numpy as np

class Sigmoid:
  def __init__(self):
    self.params, self.grads, self.out = [], [], None

  def forward(self, x):
    self.out = 1 / (1 + np.exp(-x))
    return self.out

  def backward(self, dout):
    return dout * self.out * (1.0 - self.out)

In [ ]:
class Affine :
  def __init__(self, W, b):
    self.params = [W, b]
    self.grads = [np.zeors_like(W), np.zeros_like(b)]
    self.x = None

  def forward(self, x):
    W, b = self.params
    output = x @ W +B
    self.x = x
    return output

  def backward(self, dout):
    W,b = self.paramns
    dx = np.matmul(dout, W.T)
    dW = np.matmul(self.x.T, dout)
    db = np.sum(douut, axis = 0)

    self.grads[0][...] = dW
    self.grads[1][...] = db
    return dx

조금 전에 만든 Sigmoid와 Affine 계층에 역전파 기능을 가하기 위해 각각 backward 함수를 구현하기

SGD(Stochastic Gradient Descent; 확률적경사하강법)

Spiral Dataset으로 Multi-class 분류신경망을 학습

In [ ]:
import sys
sys.path.append('..')
import numpy as np
from common.layers import Affine, Sigmoid, SoftmaxWithLoss
from dataset import spiral
import matplotlib.pyplot as plt

x, t = spiral.load_data()
print(f"x.shape: {x.shape}")
print(f"t.shape: {t.shape}")
print(f'x[0]: {x[0]}, t[0]: {t[0]}')

ModuleNotFoundError: ignored

In [ ]:
# 데이터점 플롯


In [ ]:
# 스파이럴 데이터셋을 분류하는 은닉층 한 개의 신경망 구현


In [ ]:
# 해당 코드의 학습을 수행


In [ ]:
# 학습 결과 플롯


# 경계 영역 플롯


# 데이터점 플롯



In [ ]:
# common/trainer.py의 Trainer 클래스를 활용



In [ ]:
# 비트 정밀도의 변경



# CH 02